### ISSUE TITLE
Hook every method of given package

### ISSUE THREAD

**Issue by tmfulton** [UMLGenerator/Android-UML-Generator#10]
Read the list of class names and methods, so that Xposed can hook each one, in order to know when it is called, and thus generate the XMI

**Comment by mformetal** [comment]
This has already been accomplished, as far as I know. I won't close it in case I missed some corner/ edge cases, but it worked for our test application, don't see why it wouldn't work for any other application.

**Comment by mformetal** [comment]
No update on whether my previous comment will raise an issue, and I haven't seen any problems, so gonna close this.
