### ISSUE TITLE
Turn text document creation into XMI creation

### ISSUE THREAD

**Issue by tmfulton** [UMLGenerator/Android-UML-Generator#12]
Scrap the code for printing out text, and print out XMI information instead

**Comment by JakeShor** [comment]
This issue is to transform the construction of our basic test file into that of a full XMI/XML documented file.  This will be used as our actual result from the first piece of our program, to later be combined with a program that can read XMI/XML format to convert it into a UML Sequence diagram.

**Comment by JakeShor** [comment]
6d2fffa32a97d2267166147937bcfb2db1c5eb18

**Comment by mformetal** [comment]
This hasn't been completed yet. We don't have an XMI-formatted file. We have some XML being written, but not to the specifications shown by http://www.omg.org/spec/XMI/2.1/

**Comment by JakeShor** [comment]
Ok, we've completed the aspect of this that is converting the basic test text document to a more technical format.  We're in the midst of completing the XML format, and converting that to XMI for use in StarUML
