### ISSUE TITLE
Finetune XMI format into format needed for XMI -> UML conversion 

### ISSUE THREAD

**Issue by tmfulton** [UMLGenerator/Android-UML-Generator#13]

**Comment by JakeShor** [comment]
This issue is a copy of another existing issue.  I will link that issue here and then close this issue.  https://github.com/tmfulton/Android-UML-Generator/issues/26

**Comment by mformetal** [comment]
My bad. Didn't mean to reopen this.

**Comment by JakeShor** [comment]
This is no longer necessary, as we create a UML diagram from plantUML syntax, rather than XMI.
