### ISSUE TITLE
Implement XMI -> UML conversion on device

### ISSUE THREAD

**Issue by tmfulton** [UMLGenerator/Android-UML-Generator#15]

**Comment by mformetal** [comment]
We can only do this if we use an an Android-compatible XMI->UML converter, like Jake's PlantUML. If we still plan to write XMI information, then PlantUML is useless, and we need to come up with some sort of ConverterService that takes in XMI and writes it to UML. Besides, the project specs do say they want it in XML format; we should just focus on that, as that's a more universal exchange format than PlantUML's syntax.
