### ISSUE TITLE
find example code/projects showing how to generate UML from XML

### ISSUE THREAD

**Issue by Caedus13** [UMLGenerator/Android-UML-Generator#20]
This issue is in reference to our possible usage of PlantUML to generate a UML diagram directly from what we write to our file using xposed.  If we write a file in the PlantUML language, we can use that to create the UML diagram.  If we then take that diagram, we can parse it for its XML/XMI data in order to still have that piece of information to manipulate with further aspects of the program.

**Comment by tmfulton** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.1" xmlns:uml="http://schema.omg.org/spec/UML/2.0" xmlns:xmi="http://schema.omg.org/spec/XMI/2.1">
	<xmi:Documentation exporter="StarUML" exporterVersion="2.0"/>
	<uml:Model xmi:id="AAAAAAFT02/rcBV/fss=" xmi:type="uml:Model" name="RootModel">
		<packagedElement xmi:id="AAAAAAFF+qBWK6M3Z8Y=" name="Model" visibility="public" xmi:type="uml:Model">
			<packagedElement xmi:id="AAAAAAFT023gEROI1y4=" name="Class 1" visibility="public" isAbstract="false" isFinalSpecialization="false" isLeaf="false" xmi:type="uml:Class" isActive="false"/>
			<packagedElement xmi:id="AAAAAAFT025LMRO89ko=" name="Class3" visibility="public" isAbstract="false" isFinalSpecialization="false" isLeaf="false" xmi:type="uml:Class" isActive="false">
				<ownedMember xmi:id="AAAAAAFT026QuRQnT40=" name="Dowork" visibility="public" xmi:type="uml:Association" isDerived="false">
					<ownedEnd xmi:id="AAAAAAFT026QuRQoho0=" visibility="public" isStatic="false" isLeaf="false" isReadOnly="false" isOrdered="false" isUnique="false" xmi:type="uml:Property" aggregation="composite" isDerived="false" isID="false" type="AAAAAAFT025LMRO89ko="/>
					<ownedEnd xmi:id="AAAAAAFT026QuRQpLJs=" visibility="public" isStatic="false" isLeaf="false" isReadOnly="false" isOrdered="false" isUnique="false" xmi:type="uml:Property" aggregation="none" isDerived="false" isID="false" type="AAAAAAFT023gEROI1y4="/>
					<memberEnd xmi:idref="AAAAAAFT026QuRQoho0="/>
					<memberEnd xmi:idref="AAAAAAFT026QuRQpLJs="/>
				</ownedMember>
			</packagedElement>
			<packagedElement xmi:id="AAAAAAFT025oVhPmEzg=" name="Interface1" visibility="public" isAbstract="false" isFinalSpecialization="false" isLeaf="false" xmi:type="uml:Interface"/>
			<packagedElement xmi:id="AAAAAAFT0283uhSt5r0=" name="Interface2" visibility="public" isAbstract="false" isFinalSpecialization="false" isLeaf="false" xmi:type="uml:Interface"/>
			<packagedElement xmi:id="AAAAAAFT029uphUZ3t8=" name="Class2" visibility="public" isAbstract="false" isFinalSpecialization="false" isLeaf="false" xmi:type="uml:Class" isActive="false">
				<ownedMember xmi:id="AAAAAAFT02+VqxVYjc0=" name="Dumb" visibility="public" xmi:type="uml:Dependency" client="AAAAAAFT029uphUZ3t8=" supplier="AAAAAAFT023gEROI1y4="/>
			</packagedElement>
		</packagedElement>
	</uml:Model>
</xmi:XMI>

**Comment by JakeShor** [comment]
This issue is theoretically no longer necessary, if we're definitely not going to be working with PlantUML, and are instead planning to work with StarUML and convert to the actual UML diagram after creating XML

**Comment by mformetal** [comment]
Wouldn't this still be necessary? This issue was merely to give examples of XML files that convert correctly to UML diagrams as a point of reference. We have one file that I think Tim created/ found, but more examples are never a bad thing.

**Comment by JakeShor** [comment]
here is the xmi code for an example sequence diagram from starUML: [sequencetest1.txt](https://github.com/tmfulton/Android-UML-Generator/files/209264/sequencetest1.txt)

and the associated image for it: 
![sequencediagram1](https://cloud.githubusercontent.com/assets/17186093/14367644/28a73df4-fce7-11e5-8ef0-72a5a53ee5a1.png)

**Comment by Caedus13** [comment]
Using staruml format for xmi
