### ISSUE TITLE
plan XML format and implement writing of XML to file

### ISSUE THREAD

**Issue by Caedus13** [UMLGenerator/Android-UML-Generator#26]
currently only writing 1 line; figure out why

**Comment by mformetal** [comment]
Isn't Tristan working on this?

**Comment by Caedus13** [comment]
yeah thats me
sorry for username

**Comment by JakeShor** [comment]
This Issue is to parse the necessary requirements for XML format that is required for StarUML and format our file writer in the code to the necessary specifications such that we'd be able to write our file, then immediately load it properly in StarUML with its UML diagram.

**Comment by JakeShor** [comment]
here is the xmi code for an example sequence diagram from starUML: [sequencetest1.txt](https://github.com/tmfulton/Android-UML-Generator/files/209264/sequencetest1.txt)

and the associated image for it: 
![sequencediagram1](https://cloud.githubusercontent.com/assets/17186093/14367644/28a73df4-fce7-11e5-8ef0-72a5a53ee5a1.png)

**Comment by JakeShor** [comment]
![sequencediagram2](https://cloud.githubusercontent.com/assets/17186093/14368269/ab963406-fcea-11e5-8876-a969ff13d621.png)
[sequencediagram2.txt](https://github.com/tmfulton/Android-UML-Generator/files/209302/sequencediagram2.txt)

**Comment by Caedus13** [comment]
a lifeline is a class
a message is a method, with receiveEvent the fragment on the class it instantiates and sendEvent the fragment on the class it belongs to
a fragment is the location on the class part of the diagram that a method arrow touches. it covers said class

**Comment by Caedus13** [comment]
We are now writing XMI and already know what format we are using
