### ISSUE TITLE
Implement XMI writing

### ISSUE THREAD

**Issue by Caedus13** [UMLGenerator/Android-UML-Generator#47]
In order to write XMI we need the determine the class a method instantiates. With this information we can then write XMI to the file

**Comment by JakeShor** [comment]
The parser should be setup properly now, u can find it in UMLConverter branch.  We'll need to talk to connect it to the format you specifically need for XMI, but the data should be logged properly as is

**Comment by Caedus13** [comment]
we are now writing XMI to file
https://github.com/UMLGenerator/Android-UML-Generator/commit/f21a02f6bf310b56c86209037618e17ff3c96c69
