### ISSUE TITLE
Initialize Xposed data parser

### ISSUE THREAD

**Issue by JakeShor** [UMLGenerator/Android-UML-Generator#48]
This is the first piece to mapping out the data received from Xposed into the actual data we'll write to the file.  Once this is setup, we'll be able to parse the data from Xposed into the required organization for either the PlantUML or the XMI output.  This piece is simply to map it out in an understandable way.

**Comment by mformetal** [comment]
Hasn't this already been done? The XposedLoader passes class and method info that the FileManager can then write.

**Comment by JakeShor** [comment]
Different calls to the FileWriter need to know about the previous and later calls as well in order to have all the data correctly written in each line.  Because of this, we have to create our own parser to momentarily stores the pieces of data we want to re-use.

**Comment by mformetal** [comment]
Word, makes sense. Has there been any progress? We need to have this part done by this weekend at the latest.

**Comment by JakeShor** [comment]
Basics are now setup, extra checks will require additional features to our xposed module b49ba4f0ba873c524b55307104f1512e1640aba2
