### ISSUE TITLE
Add Xposed check for ClassBeforeCalled and ClassAfterCalled

### ISSUE THREAD

**Issue by JakeShor** [UMLGenerator/Android-UML-Generator#49]
for the parser to provide its final check, I'll need to know when a given class initialization ends.  In order to do this, we'll need to mess with the Xposed module, in the xposedService file and related files.

**Comment by mformetal** [comment]
Closed by https://github.com/UMLGenerator/Android-UML-Generator/commit/d8f68aa99ed932939c0ff51534b22b06bbd38dc6
