### ISSUE TITLE
Figure out how we're going to get XMI

### ISSUE THREAD

**Issue by mformetal** [UMLGenerator/Android-UML-Generator#50]
Currently, Tristan (Caedus13) is working on writing XMI 2.1 directly to file. However, that Xmi file, when imported in starUML, cannot automatically generate a UML .png diagram without a lot of user interaction on our end (i.e. dragging and dropping elements). In effect, we have no way to determine whether the XMI that Tristan writes is well-formed. 

However, plantUML allows the conversion of an plant.txt file into a plant.xmi file, but only for simple class-type files: 
[plantUMLTest.txt](https://github.com/UMLGenerator/Android-UML-Generator/files/219463/plantUMLTest.txt)

Which converts to this UML diagram: 
![plantumltest](https://cloud.githubusercontent.com/assets/8823833/14534438/386ebf28-0237-11e6-8fa2-34d1781893bd.png)

Which then converts to this XMI diagram (currently in .txt format which github supports, you'll have to convert to .xmi on your end)
[plantUMLTestX.txt](https://github.com/UMLGenerator/Android-UML-Generator/files/219470/plantUMLTestX.txt)

This spits out XMI 1.3, which can be converted into XMI 2.1 using certain tools like: http://www.baptisteautin.com/projets-personnels/php_uml/convertisseur-de-fichier-xmi/lang/en/

**Comment by mformetal** [comment]
Class diagram writing syntax: http://plantuml.com/classes.html

**Comment by JakeShor** [comment]
we write an xmi file that gets outputted now 1b87cb2978a20118ab021d730508d992f50eda4c
