### ISSUE TITLE
implement plantUML writing

### ISSUE THREAD

**Issue by Caedus13** [UMLGenerator/Android-UML-Generator#56]
don't see an issue for this specifically so adding it. we need to write the text that translates to a plantUML diagram. This should be relatively simple as we have the data already from writing the XMI and plantUML takes a very simple format. a method like this:

public void addInstantiationPlantUML(Class fromClass, Class toClass, Method method) {
    writeString += fromClass.getName() + "->" + toClass.getName() + ": " + method.getName() + "\n";
}

called each time the comparable XMI-writing method is called should generate the plantUML text for a sequence diagram

**Comment by JakeShor** [comment]
This is now working 9d97b48b7fc80250fded9a9fcfdd98eb0ff375e1
