### ISSUE TITLE
Get PlantUML output properly formatted

### ISSUE THREAD

**Issue by JakeShor** [UMLGenerator/Android-UML-Generator#59]
There were some issues with the output of the plantUML file outputed by the app, so that it wouldn't be able to get read by plantUML.  This must be resolved.  Some of the issues included changed the $ to _ so that plantUML won't throw an error.

**Comment by JakeShor** [comment]
The current version of the plantUML branch (9d97b48b7fc80250fded9a9fcfdd98eb0ff375e1) is now able to output a file such as this:
[catInHatPlantUML.txt](https://github.com/UMLGenerator/Android-UML-Generator/files/225089/catInHatPlantUML.txt)
  which can be read by plantUML to create this image:
![catinhatplantuml](https://cloud.githubusercontent.com/assets/17186093/14625252/77c368ce-05af-11e6-8dc9-2110cea227bb.png)

**Comment by JakeShor** [comment]
my mockup of what should be the correct output using starUML and manually creating the sequence diagram is:
![catinhat](https://cloud.githubusercontent.com/assets/17186093/14625263/933475b2-05af-11e6-9b36-6eaffdf845bf.png)
with the associated starUML xmi:

[catInHat.txt](https://github.com/UMLGenerator/Android-UML-Generator/files/225093/catInHat.txt)

**Comment by JakeShor** [comment]
To me, it seems they are the same.

**Comment by JakeShor** [comment]
also here is the program i ran, in case anyone wants to retest it: https://github.com/JakeShor/CatInHat.git

**Comment by JakeShor** [comment]
Ok, here's an update to the existing plantUML output that seperates class instances 849a127434b0ba7db35837267ab5024bfd66a237
![newcatinhat](https://cloud.githubusercontent.com/assets/17186093/14652236/785c17ee-0641-11e6-937c-0999cadd0661.png)
and the .txt file: 
[newCatInHat.txt](https://github.com/UMLGenerator/Android-UML-Generator/files/226646/newCatInHat.txt)

**Comment by mformetal** [comment]
I already said as much on the FB chat, but I think I'll need to change how I'm passing data from the XposedModule; it seems that it's passing an anonymous inner class because of the onClickListener interface instead of the outer class, i.e. MainActivity$1 instead of MainActivity.

**Comment by JakeShor** [comment]
Additionally, I just added the appropriate end tag to be appended to the file 15a5890f07dee7e145a8153cb620797ffc018d51

**Comment by JakeShor** [comment]
As we mentioned at the Wednesday meeting, I've added the legend tag to the plantUML now:
![newcatinhatwithlegend](https://cloud.githubusercontent.com/assets/17186093/14691805/60f04838-0721-11e6-87f0-39fc795b1569.png)

and its associated .txt file: 
[newCatInHatWithLegend.txt](https://github.com/UMLGenerator/Android-UML-Generator/files/228874/newCatInHatWithLegend.txt)

**Comment by JakeShor** [comment]
this is finished now c34eacad5ddfc4e0e68484193c489bbf4c556365
