### ISSUE TITLE
Abstract out file writing into enclosed classes

### ISSUE THREAD

**Issue by mformetal** [UMLGenerator/Android-UML-Generator#60]
Currently, FileManager directly writes to respective PlantUML and XML files. It would be much better if it didn't directly write them, but instead called a class's methods to do so. Current idea:

1) Have a base abstract Writer class with a couple abstract method-contracts.

2) Extend from that Writer class to write in different formats - XML, plantUML, etc.

3) Give FileManager a list of these Writer classes, and, when appropriate, call them to write to the file.

**Comment by Caedus13** [comment]
A useful way I was thinking to implement this abstraction was to have:
a) a WriterUtils class with methods to implement our logic 
     -methods for determining the class-method-class relation
     -methods for writing to plantUML and XMI
b) a Writer abstract class and abstract methods
c) our extension of the Writer class, implementing methods and calling the methods from the WriterUtils class to perform the logic.
d) FileManager would only be calling our extension of the writer class

This way, we avoid having all the logic in FileManager, Writer can be extended and implemented based on the desired output(s), and all we'd need to do to change what outputs we write to was change what WriterUtil methods we call in our Writer subclass.

**Comment by JakeShor** [comment]
Should be done now 988036ca8dddee19b4be9f68f22afa9c84e8e528
