### ISSUE TITLE
Create GUI application

### ISSUE THREAD

**Issue by tmfulton** [UMLGenerator/Android-UML-Generator#7]
Application must:
- Provide list of all applications on phone
- Provide start and stop button

**Comment by mformetal** [comment]
Working on this now, should have it done by the end of the day. Although, I don't think a "start"/ "stop" button is required. Xposed already detects package loading, and I'm assuming automatically stops itself when needed. Perhaps a "start with given package" button, and "print uml" button is more necessary?

Basic functionality is done. We'll need to talk with Carlos about the specifics about exactly which applications he wants to be able to use xposed on; some applications don't have an explicitly labeled launch intent, so the user couldn't track those anyway. 

After further work, I don't think we even need a "stop" button. When you want to get your UML diagram, just exit the app and run whatever "XMI to UML" conversion program we'll end up using.

All changes related to this issue should been the branch GUI.

**Comment by mformetal** [comment]
Gonna go ahead and close this. It's been done for a while, just didn't want to close it too early.
